frr version 10.5.1
frr defaults traditional
hostname R1
log syslog informational
service integrated-vtysh-config
!
router rip
 network 10.1.12.0/30
 network 10.1.14.0/30
 network 192.168.1.0/24
 passive-interface enp0s3
 version 2
 exit
!
end
